### ISSUE TITLE
Error with the PostGresQL Driver not available

### ISSUE THREAD

**Issue by balessan** [sovity/edc-extensions#159]
# Bug Report

After following the tutorial from the Mobility Data Space here and deploying our own environment on kamatera to have something online to play with and better understand the interactions between multiple connectors. When starting the projet using the provided docker-compose configuration however, I get an error.

## Description

Current status is that, upon running the project using the `docker compose up` command, the EDC container is failing on the following error:

```sh
edc         | 2023-03-01 14:46:59 Error booting runtime: java.sql.SQLException: No suitable driver found for  
edc         | org.eclipse.edc.spi.persistence.EdcPersistenceException: java.sql.SQLException: No suitable driver found for 
edc         | 	at de.sovity.edc.extension.postgresql.connection.DriverManagerConnectionFactory.create(DriverManagerConnectionFactory.java:44)
edc         | 	at org.eclipse.edc.sql.datasource.ConnectionFactoryDataSource.getConnection(ConnectionFactoryDataSource.java:40)
edc         | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
edc         | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
edc         | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:146)
edc         | 	at org.flywaydb.core.Flyway.baseline(Flyway.java:297)
edc         | 	at de.sovity.edc.extension.postgresql.migration.FlywayService.migrateDatabase(FlywayService.java:51)
edc         | 	at de.sovity.edc.extension.postgresql.migration.DatabaseMigrationManager.migrateAllDataSources(DatabaseMigrationManager.java:36)
edc         | 	at de.sovity.edc.extension.postgresql.PostgresFlywayExtension.initialize(PostgresFlywayExtension.java:33)
edc         | 	at org.eclipse.edc.boot.system.injection.lifecycle.InitializePhase.initialize(InitializePhase.java:37)
edc         | 	at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.initialize(ExtensionLifecycleManager.java:61)
edc         | 	at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.initialize(ExtensionLifecycleManager.java:61)
................
edc         | 	at de.sovity.edc.extension.postgresql.connection.DriverManagerConnectionFactory.create(DriverManagerConnectionFactory.java:42)
edc         | 	... 24 more
edc         | 
edc exited with code 255
```

Being a complete newbie in Java, I cannot figure out how to workaround that one (I did a few tricks on the certificates generation mecanism to get the proper JKS). Pretty sure something evident is missing

### Expected Behavior

The EDC container should run, as expected without any critical errors.

1. Clone the project
2. Follow the steps from the documentation here to get the certificate
3. Launch the containers using `docker compose up`

## Context Information

_Add any other context about the problem here._

- Environment: Dev but online on Katamera
- OS: Ubuntu Server with Docker and Docker-compose installed, plus headless JRE-8
- ...

**Comment by balessan** [comment]
Can confirm I am getting the same issue locally. In terms of configuration, apart from what is suggested in the documentation I am not modifying anything.

For more information, my adaptation of the docker-compose looks as follow:

```yml
version: "3.8"
services:
  edc-ui:
    image: ghcr.io/sovity/edc-ui:latest
    container_name: edc-ui
    ports:
      - '11000:80'
    environment:
      - EDC_UI_ASSET_PROP_ORIGINATOR_ORGANIZATION=Startin'blox
      - EDC_UI_ACTIVE_PROFILE=mds-open-source
      - EDC_UI_DATA_MANAGEMENT_API_URL=http://localhost:11002/api/v1/data
      - EDC_UI_DATA_MANAGEMENT_API_KEY=ApiKeyDefaultValue
      - EDC_UI_CATALOG_URLS=http://edc.startinblox.com:11003/api/v1/ids/data
      - EDC_UI_ASSET_PROP_ORIGINATOR=http://edc.startinblox.com:11003/api/v1/ids/data
  edc:
    container_name: edc
    image: ghcr.io/sovity/edc-mds:latest
    environment:
      # Basic Configuration
      EDC_IDS_TITLE: 'Startinblox EDC Connector'
      EDC_CONNECTOR_NAME: 'Startinblox EDC Connector'
      EDC_IDS_DESCRIPTION: 'A Startinblox compliant demonstration connector'
      EDC_IDS_CURATOR: https://startinblox.com
      EDC_HOSTNAME: edc.startinblox.com
      EDC_IDS_ENDPOINT: http://edc.startinblox.com:11003/api/v1/ids
      EDC_API_AUTH_KEY: ApiKeyDefaultValue

      # Data Space Configuration
      EDC_OAUTH_CLIENT_ID: 2E:90:7D:69:82:1A:44:DE:71:16:17:CF:C9:00:77:D1:B7:38:05:BB:keyid:6D:2B:39:5A:A7:7A:BA:F4:9D:95:DA:AF:8C:42:9F:C8:8A:68:18:87
      EDC_KEYSTORE: /resources/vault/edc/edc-dev.startinblox.com.jks
      EDC_OAUTH_TOKEN_URL: https://daps.test.mobility-dataspace.eu/token
      EDC_OAUTH_PROVIDER_JWKS_URL: https://daps.test.mobility-dataspace.eu/jwks.json
      EDC_BROKER_BASE_URL: https://broker.test.mobility-dataspace.eu
      EDC_CLEARINGHOUSE_LOG_URL: https://clearing.test.mobility-dataspace.eu/messages/log

      # Deployment Configuration
      WEB_HTTP_PORT: 11001
      WEB_HTTP_PATH: /api
      WEB_HTTP_DATA_PORT: 11002
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 11003
      WEB_HTTP_IDS_PATH: /api/v1/ids
      EDC_IDS_ID: urn:connector:example-connector
      IDS_WEBHOOK_ADDRESS: http://edc:11003
      EDC_IDS_MAINTAINER: https://sovity.de
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
      EDC_VAULT: /resources/vault/edc/vault.properties
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_PUBLIC_KEY_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
      EDC_FLYWAY_POSTGRES_JDBC_URL: jdbc:postgresql://postgresql:5432/edc
      EDC_FLYWAY_POSTGRES_JDBC_USER: edc
      EDC_FLYWAY_POSTGRES_JDBC_PASSWORD: edc
    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '5005:5005'
    volumes:
      - ./resources:/resources
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: postgresql
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    volumes:
      - 'postgresql:/bitnami/postgresql'

volumes:
  postgresql:
    driver: local
```
