### ISSUE TITLE
URI of the Dataset freezes

### ISSUE THREAD

**Issue by balessan** [sovity/edc-extensions#161]
# Bug Report

## Description

Once the project is deployed and running, I tried creating assets (it works) but I cannot figure out the API URI to use to access the dataset itself.

Both dataset and connectors are available through the MDS broker:

- https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F-1179781081
- https://catalog.test.mobility-dataspace.eu/resources/resource?id=https://broker.test.mobility-dataspace.eu/catalog/-1179781081/1902456861/526382240

But we do not get how to access the Data itself from the dataset.
Given the current configuration, the data API looks unavailable but we are not sure how to configure it.

Those API endpoints never returns anything usable:

- https://edc-dev.startinblox.com/catalog/MySuperContract-urn:artifact:superduperdataset
- http://edc-dev.startinblox.com:11003/api/v1/ids/data

### Expected Behavior

As we understood it, the URL https://edc-dev.startinblox.com/catalog/MySuperContract-urn:artifact:superduperdataset should actually give you access to the description of the data, or to the data itself ?

### Observed Behavior

It just freezes. Blank screen.

## Context Information

The docker-compose.yml looks like:

```yml
  edc-ui:
    image: ghcr.io/sovity/edc-ui:latest
    container_name: edc-ui
    ports:
      - '11000:80'
    environment:
      - EDC_UI_ASSET_PROP_ORIGINATOR_ORGANIZATION=Startinblox Dev Connector
      - EDC_UI_ACTIVE_PROFILE=mds-open-source
      - EDC_UI_DATA_MANAGEMENT_API_URL=http://edc-dev.startinblox.com:11002/api/v1/data
      - EDC_UI_DATA_MANAGEMENT_API_KEY=ApiKeyDefaultValue
      - EDC_UI_CATALOG_URLS=http://edc-dev.startinblox.com:11003/api/v1/ids/data
      - EDC_UI_ASSET_PROP_ORIGINATOR=http://edc-dev.startinblox.com:11003/api/v1/ids/data
  edc:
    container_name: edc
    image: ghcr.io/sovity/edc-mds:latest
    environment:
      # Basic Configuration
      EDC_IDS_TITLE: 'Startinblox EDC Connector'
      EDC_CONNECTOR_NAME: 'Startinblox EDC Connector'
      EDC_IDS_DESCRIPTION: 'Minimal configured Open Source EDC built by sovity'
      EDC_IDS_CURATOR: https://startinblox.com
      EDC_HOSTNAME: edc-dev.startinblox.com
      EDC_IDS_ENDPOINT: http://edc-dev.startinblox.com:11003/api/v1/ids
      EDC_API_AUTH_KEY: ApiKeyDefaultValue

      # Data Space Configuration
      EDC_OAUTH_CLIENT_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
      EDC_KEYSTORE: /resources/vault/edc/edc-dev.startinblox.com.jks
      EDC_OAUTH_TOKEN_URL: https://daps.test.mobility-dataspace.eu/token
      EDC_OAUTH_PROVIDER_JWKS_URL: https://daps.test.mobility-dataspace.eu/jwks.json
      EDC_BROKER_BASE_URL: https://broker.test.mobility-dataspace.eu
      EDC_CLEARINGHOUSE_LOG_URL: https://clearing.test.mobility-dataspace.eu/messages/log

      # Deployment Configuration
      WEB_HTTP_PORT: 11001
      WEB_HTTP_PATH: /api
      WEB_HTTP_DATA_PORT: 11002
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 11003
      WEB_HTTP_IDS_PATH: /api/v1/ids
      EDC_IDS_ID: urn:connector:example-connector
      IDS_WEBHOOK_ADDRESS: http://edc-dev.startinblox.com:11003
```

Thanks in advance.
